// <auto-generated />
namespace HootHoot_CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _18thJUNE0723HRSAddFOREIGNKEYStoQuestionsmodelfromtheOptionTypeandQuestionTypemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18thJUNE0723HRSAddFOREIGNKEYStoQuestionsmodelfromtheOptionTypeandQuestionTypemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201606172324151_18th JUNE 0723 HRS - Add FOREIGN KEYS to Questions model from the OptionType and QuestionType model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
