// <auto-generated />
namespace HootHoot_CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _18thJUN0656HRSAddOptionTypeQuestionTypemodelReferencedtoQuestionsmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18thJUN0656HRSAddOptionTypeQuestionTypemodelReferencedtoQuestionsmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201606172257447_18th JUN 0656 HRS - Add OptionType,QuestionType model Referenced to Questions model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
