// <auto-generated />
namespace HootHoot_CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201606141429hrs_AmendTableColumnName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201606141429hrs_AmendTableColumnName));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140620200_201606141429hrs_AmendTableColumnName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
