// <auto-generated />
namespace HootHoot_CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _18thJune0131hrs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18thJune0131hrs));
        
        string IMigrationMetadata.Id
        {
            get { return "201606171732298_18th June 0131 hrs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
